### ISSUE TITLE
Grammar correction in documentation

### ISSUE THREAD

**Issue by BoredBored** [boostorg/stacktrace#109]
Section: Handle terminates, aborts and Segmentation Faults
https://www.boost.org/doc/libs/1_75_0/doc/html/stacktrace/getting_started.html#stacktrace.getting_started.handle_terminates_aborts_and_seg

In the warning it says:
> Only a few system calls allowed in signal handlers,

The correct way to say this is:
> Only a few system calls *are* allowed in signal handlers,

**Comment by apolukhin** [comment]
Thanks for the report!

That sentence has gone in latest docs https://www.boost.org/doc/libs/1_76_0/doc/html/stacktrace/getting_started.html
