### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ycyclop** [boostorg/stacktrace#111]
When I do a simple stacktrace there is a memory leak that I do not expect:
```
int main()
{
    int counter = 0;
    while (counter < 1000)
    {
        std::cout << boost::stacktrace::stacktrace();
        counter++;
    }
}
```
in debug the application starts with a footprint of ~40k, at the end it raises to ~440k and as you can see all it does is call the stacktrace().
In my full application I fear it has some other impact on the memory like corruption that causes the application to misbehave after ~1000 calls but I didn't manage to reproduce it in a smaller scale. The issue I encountered is eliminated when I remove this call `std::cout << boost::stacktrace::stacktrace();` in my real application.

This is on a MSVC 2019 environment. toolset v142

**Comment by apolukhin** [comment]
Fixed in 27093f24cb2ff187b179ffc561bdf0c27d7cf551

Will update the docs soon
