### ISSUE TITLE
clang and libbacktrace detection

### ISSUE THREAD

**Issue by bgemmill** [boostorg/stacktrace#115]
I'm trying to build boost with clang and get the library `boost_stacktrace_backtrace` at the end.

If we use a process like this to just build stacktrace:
```
./bootstrap.sh --with-toolset=clang
cd libs/stacktrace/build
../../../b2 -a libbacktrace
```

We get the error:
`../../../libs/stacktrace/build/has_backtrace.cpp:7:10: fatal error: 'backtrace.h' file not found`

Which makes sense, given that `backtrace.h` lives in gcc's library location, and not clang's. 

The issue is that there does not seem to be a set of b2 options that will fix this issue for clang, because [has_backtrace.cpp](https://github.com/boostorg/stacktrace/blob/develop/build/has_backtrace.cpp#L7) does not use `BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE` like the [rest of stacktrace does](https://github.com/boostorg/stacktrace/blob/develop/include/boost/stacktrace/detail/libbacktrace_impls.hpp#L20-L24).

This means that even if a user tries to point b2 to libbacktrace via `define=BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE=...` as documented [here](https://www.boost.org/doc/libs/1_77_0/doc/html/stacktrace/configuration_and_build.html#ftn.stacktrace.configuration_and_build.f3), has_backtrace.cpp will still fail to detect anything.

Could has_backtrace.cpp please be changed to use BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE?

**Comment by apolukhin** [comment]
Many thanks for the bugreport!

**Comment by bgemmill** [comment]
Thanks for fixing that!

**Comment by gysevvlad** [comment]
Sorry for necroposting, but I want to clarify one moment.
How I can pass quotes ("") to  `BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE` via `b2 define=...`?
`linux` defined as 1, look at:)
```
../../../libs/stacktrace/build/has_backtrace.cpp:8:13: fatal error: '/usr/lib/gcc/x86_64-1-gnu/12/include/backtrace.h' file not found
#   include BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<command line>:2:49: note: expanded from here
#define BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE </usr/lib/gcc/x86_64-linux-gnu/12/include/backtrace.h>
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Clang 14, Ubuntu 22
