### ISSUE TITLE
Memory leak due to calling `backtrace_create_state` multiple times

### ISSUE THREAD

**Issue by Cogitri** [boostorg/stacktrace#118]
Hello,

currently boost-stacktrace with the `backtrace` backend will call [backtrace_create_state](https://github.com/boostorg/stacktrace/blob/08d720adbd01c0187af256eb491cffece7e87857/include/boost/stacktrace/detail/libbacktrace_impls.hpp#L104) once for each thread. This creates a memory leak since each time a new thread is created, a new `backtrace_state` is allocated but it's never freed (and can't be since there's no `backtrace_destroy_state`).  See e.g. https://patchwork.ozlabs.org/project/gcc/patch/3defaafeedc9fa6b42e61401d4c8c84e@starynkevitch.net/#1625428 for more discussion on this.

**Comment by pergraa-celonis** [comment]
Should that be `static` and not `ststic` here?
https://github.com/boostorg/stacktrace/commit/308b7f6b087a302795d6a189373f254f610a826f#diff-1f3dccb3928ad7b52e4c986270cb619b663197283b764c2fb68256d285f21a3fR124

**Comment by apolukhin** [comment]
Oops, thanks!
