### ISSUE TITLE
BOOST_STACKTRACE_USE_WINDBG is missing in windbg.cpp

### ISSUE THREAD

**Issue by deadlocklogic** [boostorg/stacktrace#135]
https://github.com/boostorg/stacktrace/blob/95065ca63883c0b1d6754bdb7bb106058c7532cb/src/windbg.cpp#L1-L10 is missing:
```cpp
#define BOOST_STACKTRACE_USE_WINDBG 
```

**Comment by deadlocklogic** [comment]
Just another issue:
CMake doesn't take into consideration: `BOOST_STACKTRACE_LINK` flag, so the the `.cpp` file are compiled anyway which leads to `multiple definition` error on `MINGW`.

**Comment by apolukhin** [comment]
Not sure that `#define BOOST_STACKTRACE_USE_WINDBG` as there are some cygwin usages that use libunwind interfaces. Looks like it works as is.

As for the second issue - please provide a fix for it, I can not reproduce it.
