### ISSUE TITLE
gcc warnings with -Wshadow compiler flag

### ISSUE THREAD

**Issue by nigels-com** [boostorg/stacktrace#141]
Looking at `safe_dump_to.hpp` there is a recurring pattern there of doing:

```
        typedef boost::stacktrace::detail::native_frame_ptr_t native_frame_ptr_t;
```

Which is understandable, on the face of it, improving clarity.

On the other hand, our codebase is using -Wshadow compiler flag on Linux and it is complaining about this in `boost::stacktrace` eventhough it's arguably a false alarm.

But looking more closely, we're already in the `boost::stacktrace::detail` namespace, are these additional typedefs still necessary?

**Comment by apolukhin** [comment]
Many thanks for the report!
