### ISSUE TITLE
stacktrace_from_exception contains misleading assert-message

### ISSUE THREAD

**Issue by Ukilele** [boostorg/stacktrace#164]
There is a BOOST_ASSERT_MSG here: https://github.com/boostorg/stacktrace/blob/39afcefb6413b773b9f464689e994698a7a2ddc8/src/from_exception.cpp#L236-L238

Isn't `sizeof(void*)` equal to 4 on 32bit platforms and 8 on 64bit platforms? The assert-message reads contrary to its condition, doesn't it? I ran into this assert on a 64bit platform and got confused, because it says `"32bit platforms are unsupported [...]"`.

**Comment by apolukhin** [comment]
Ouch.

Many thanks for the bugreport, fixed in upstream
