### ISSUE TITLE
Typo in the from_current_exception example

### ISSUE THREAD

**Issue by d4nnie** [boostorg/stacktrace#173]
Example from the [docs]( https://www.boost.org/doc/libs/1_85_0/doc/html/stacktrace/getting_started.html#stacktrace.getting_started.stacktrace_from_arbitrary_except) fails to [compile](https://godbolt.org/z/T4W17h87b):
```
<source>: In function 'int main()':
<source>:14:62: error: 'from_current_exception' is not a member of 'boost::stacktrace'
   14 |     boost::stacktrace::stacktrace trace = boost::stacktrace::from_current_exception();  // <---
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~
Compiler returned: 1
```

Obviously, as said in the docs themselves, the full name for `from_current_exception` will be `boost::stacktrace::stacktrace::from_current_exception`.

**Comment by NoumanAmir657** [comment]
Can I fix this?

**Comment by apolukhin** [comment]
Fixed in https://github.com/boostorg/stacktrace/pull/181
