### ISSUE TITLE
Don't inject capture_stack.hpp in Boost.WinAPI

### ISSUE THREAD

**Issue by Lastique** [boostorg/stacktrace#20]
Please, move boost/detail/winapi/capture_stack.hpp to boost/stacktrace and also update the file contents to:

- avoid injecting symbols into `boost::detail::winapi` namespace
- avoid using `BOOST_DETAIL_WINAPI` prefix in macros
- fix the include guard

**Comment by apolukhin** [comment]
I'd rather move it to Boost.WinAPI.

What do you think about it?

**Comment by Lastique** [comment]
I've added the function to Boost.WinAPI.
