### ISSUE TITLE
Compilation error due to a missing file.

### ISSUE THREAD

**Issue by vlichevsky** [boostorg/stacktrace#29]
I am trying to compile a program that uses Boost.Stacktrace and get the following error:

    % g++ -g -I/tmp/boost/include -L/tmp/boost/lib -DBOOST_STACKTRACE_LINK -DBOOST_STACKTRACE_USE_BACKTRACE -lboost_stacktrace_backtrace -ldl -lbacktrace stacktrace-test.cpp -o stacktrace-test                
    In file included from /tmp/boost/include/boost/stacktrace/frame.hpp:20:0,
                     from /tmp/boost/include/boost/stacktrace.hpp:15,
                     from stacktrace-test.cpp:2:
    /tmp/boost/include/boost/stacktrace/safe_dump_to.hpp:15:10: fatal error: boost/stacktrace/detail/push_options.pp: No such file or directory
     #include <boost/stacktrace/detail/push_options.pp>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.

I am using Stacktrace library version that is included in Boost 1.65.0 release. Boost was built whith the following commands:
`./bootstrap.sh`
`./b2 --prefix=/tmp/boost --with-stacktrace install`
Resulting installation indeed misses files `boost/stacktrace/detail/push_options.pp` and `boost/stacktrace/detail/pop_options.pp`. Is this a bug, or am I doing something wrong?

**Comment by as-xjc** [comment]
me too in macos. Finally, I copied the two files frome src to include.

**Comment by PavlovMU** [comment]
https://svn.boost.org/trac10/ticket/13178

**Comment by vlichevsky** [comment]
Confirming that this issue is fixed in Boost 1.65.1rc1.

**Comment by apolukhin** [comment]
Thanks for reporting the issue and testing the fix!
