### ISSUE TITLE
calling stacktrace functions is very slow

### ISSUE THREAD

**Issue by Ali-Se** [boostorg/stacktrace#30]
I'm developing a solution where the call stack is stored in XML file, so I call the name(), source_file(), and source_line() functions for each frame, I takes about 45 seconds to complete the loop on stack depth of about 70 levels.

**Comment by apolukhin** [comment]
What compiler and OS are you using?

**Comment by Ali-Se** [comment]
Windows 10 + Visual Studio 2015 update 4

**Comment by apolukhin** [comment]
Try defining the BOOST_STACKTRACE_USE_WINDBG_CACHED macro or link with boost_stacktrace_windbg_cached (see http://www.boost.org/doc/libs/master/doc/html/stacktrace/configuration_and_build.html for more info).

Please report back the results.

**Comment by Ali-Se** [comment]
I got this error message:
../boost/stacktrace/detail/frame_msvc.ipp(167): fatal error C1189: #error:  Your compiler does not support C++11 thread_local storage. It's impossible to build with BOOST_STACKTRACE_USE_WINDBG_CACHED.

**Comment by apolukhin** [comment]
For compilers that do not support `thread_local` storage there's no good library way to speed up the stacktrace decoding.

However, you could cache decoded strings. Make an `unordered_map<frame, std::string>`. That should help a lot.

P.S: I'll try to implement that stacktrace caching some day. If it fits well as a generic Boost library solution - I'll merge it into the Boost.Stacktrace library.
