### ISSUE TITLE
stacktrace does not work on iOS armv7/armv7s

### ISSUE THREAD

**Issue by theodelrieu** [boostorg/stacktrace#46]
Hello,

When attempting to use the header only version of Stacktrace, I get the following linker error:

>Undefined symbols for architecture armv7:
  "__Unwind_Backtrace", referenced from:
      boost::stacktrace::detail::this_thread_frames::collect(void const**, unsigned long, unsigned long) in libmylib.a(Error.cpp.o)
ld: symbol(s) not found for architecture armv7

I did look in the `libSystem.tbd` and the `__Unwind_Backtrace` symbol is only defined for arm64.

The workaround is to define the `BOOST_STACKTRACE_USE_NOOP` macro. Is there another way to workaround the problem?

**Comment by apolukhin** [comment]
Did you link with libbacktrace and standard library?
Could you please provide a compile and link commands that trigger the issue?

**Comment by theodelrieu** [comment]
I tried to find a way to get libbacktrace for iOS (and Darwin platforms in general), but it seems upstream was not updated for a while, and the only recent patches I've seen are from a fork inside rustlang.

Do you know if there is a way to get libbacktrace working on macOS/iOS?

**Comment by ivanarh** [comment]
I've already faced this problem. A solution is to use backtrace() function from execinfo.h instead of __Unwind_Backtrace.

**Comment by apolukhin** [comment]
This should have been fixed in #70 
Please reopen if #70 does not solve issue for you. 

Many thanks for the report!
