### ISSUE TITLE
no function names with older dbgeng.dll, only addresses

### ISSUE THREAD

**Issue by zlojvavan** [boostorg/stacktrace#47]
not the bugreport, rather just for the record. I couldn't make it work on my win 7 and tried several dbgeng.dll versions to no avail until I installed fresh win ddk which did the trick for me. side effect is extra dependencies on DbgModel.dll and dbghelp.dll I've had to put into target directory to let application start. guess this could be reflected in docs as windows specific details

**Comment by apolukhin** [comment]
What version of Visual Studio you were using?

**Comment by zlojvavan** [comment]
Microsoft Visual Studio Community 2017 
Version 15.6.5
VisualStudio.15.Release/15.6.5+27428.2027
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA507
Microsoft Visual C++ 2017

**Comment by apolukhin** [comment]
@zlojvavan please take a look at the docs in aea7ab8
Does it solve your problem?

**Comment by zlojvavan** [comment]
> @zlojvavan please take a look at the docs in [9b5bc54](https://github.com/boostorg/stacktrace/commit/9b5bc54fe3050762bb617d62bb73d842be1e165b)
> Does it solve your problem?

I resolved the problem back in last february after applying emptyVoid workaround (/PDBALTPATH:%_PDB% )

**Comment by apolukhin** [comment]
Thanks for the update!
