### ISSUE TITLE
How to build boost_stacktrace_backtrace

### ISSUE THREAD

**Issue by yuwenyong** [boostorg/stacktrace#49]
libbacktrace exists on my system.

After I had built boost with default options, I found boost_stacktrace_backtrace was not built, but libboost_stacktrace_addr2line was generated.

**Comment by ArekPiekarz** [comment]
Have you seen this? https://www.boost.org/doc/libs/1_66_0/doc/html/stacktrace/configuration_and_build.html

Also when posting an issue it's helpful to include steps to reproduce the problem and information about your environment.

**Comment by yuwenyong** [comment]
yes,I have read this. I build boost on my iMac.I do the as the following steps:
1 ./bootstrap.sh
2 ./b2
3 ./b2 install
Later,I built boost on ubuntu and the lib was successful generated

**Comment by apolukhin** [comment]
@yuwenyong please help me to diagnose the problem.
Do the following steps from the boost root:
* ./bootstrap.sh
* cd libs/stacktrace/build
* ../../../b2 -a libbacktrace

The last command should produce some error message. Please paste it to this issue.

**Comment by yuwenyong** [comment]
@apolukhin  Sorry, forgot to close this issue. After doing some investigation, I find libbacktrace only supported by g++. I compile it using clang on macos, so it is not generated. However even without libbacktrace, stacktrace_basic can generate the call stack as pretty as stacktrace_backtrace.
