### ISSUE TITLE
RtlCaptureStackBackTrace is available in MinGW

### ISSUE THREAD

**Issue by volo-zyko** [boostorg/stacktrace#52]
At least in my case (GCC 6.3.0, sjlj exception handling, Window 8.1 Pro 64-bit, build targeting 32-bit environment) it compiles and works fine. On the contrary _Unwind_Backtrace in the same environment compiles but does not work.

It would be good if this were at least configurable if there are still cases when RtlCaptureStackBackTrace is not available.

https://github.com/boostorg/stacktrace/blob/e4e2d4c3c130c74f369655c1da204a64fce9937a/include/boost/stacktrace/safe_dump_to.hpp#L214

**Comment by volo-zyko** [comment]
Sorry, I was wrong. I use MinGW-w64 targeting 32-bit environment, hence the confusion. And I work with boost 1.65.1 which had in this line `!defined(BOOST_GCC)`. Changing this code to `!defined(BOOST_WINAPI_IS_MINGW)` fixed my issue.

This one can be closed as invalid.

**Comment by apolukhin** [comment]
Anyway, thanks for the second comment! It saved me from debugging :)
