### ISSUE TITLE
Boost::stacktrace does not show function name for optimize build

### ISSUE THREAD

**Issue by dyadav7** [boostorg/stacktrace#65]
Hi

I am using boost 1.67.  I am using -O option to compile. The boost::starcktrace does not show any function names. The nm command shows there are still some functions name in executable.
See output.txt file. It is generated by  "runme > output.txt" command.

I have attached the source file. I am using BOOST_STACKTRACE_USE_BACKTRACE.

[opt.tar.gz](https://github.com/boostorg/stacktrace/files/2518988/opt.tar.gz)

Regards
Deepak

**Comment by apolukhin** [comment]
What version of Boost are you using?

The issue was probably already fixed [here](https://github.com/boostorg/stacktrace/commit/745c6aa7a09aa665d8ac265dfecb4728848a417f) and will appear in the next release of Boost (1.69).

**Comment by dyadav7** [comment]
I am using 1.67 version.

**Comment by apolukhin** [comment]
As a quick workaround you could download the latest master branch of this repo and replace the content of boost_root/boost/stacktrace with this_repo/include/boost/stacktrace . Though I'm not sure that all the headers included have the same names in 1.67
