### ISSUE TITLE
How could we show line number on mac OS?

### ISSUE THREAD

**Issue by wind2412** [boostorg/stacktrace#68]
We don't have `addr2line` on macos. I wonder how we can get line information use our macro configuration. I used `brew` to install `boost`, and the version is `1.69.0`.

After `boost::stacktrace::stacktrace()`, I only get this output:

```
 0# run() in /Users/xxx/Desktop/./bin/test
 1# main in /Users/xxx/Desktop/./bin/test
```

Thanks in advance :)

**Comment by ivanarh** [comment]
atos may help
https://www.unix.com/man-page/osx/1/atos/

**Comment by narodnik** [comment]
See also #97 we get on linux too

**Comment by spinicist** [comment]
Hello, did anyone manage to resolve this? Address Sanitizer on Mac manages to get line numbers.

**Comment by apolukhin** [comment]
Was probably fixed in https://github.com/boostorg/stacktrace/commit/fbcd543b5180b8ee307fef6fbfc34aa372d330cf

If not - please reopen the issue
