### ISSUE TITLE
Stacktrace master doesn't build with msvc-9.0

### ISSUE THREAD

**Issue by pdimov** [boostorg/stacktrace#82]
This is fixed on develop, the fix just needs to be merged. 1.72 is approaching.

**Comment by pdimov** [comment]
Ping?

**Comment by apolukhin** [comment]
There's no MSVC-9 regression test runners. Because of that I treat the issue as unimportant, the fix could wait for 1.73

**Comment by apolukhin** [comment]
Fixed, merged to master
