### ISSUE TITLE
Portable Stacktrace

### ISSUE THREAD

**Issue by igoloe** [boostorg/stacktrace#92]
Hi,
is there any interest in making traces portable, so that symbolic resolution may be done later on another machine or environment with knowledge of binaries and debug symbols.
At least for windows this can be done, but i am not sure, if the same mechanisms maybe used for linux to. Besides such a serialization wont be os independent.

**Comment by apolukhin** [comment]
Sounds interesting, but I have to see the PR to be sure

**Comment by apolukhin** [comment]
Closing as a dup of #180
