### ISSUE TITLE
hangs indefinitely during configuration when cross-compiling with Visual Studio

### ISSUE THREAD

**Issue by GyrosGeier** [boostorg/stacktrace#93]
During a build attempt on amd64 for arm64 with Visual Studio:

22:17:11     - addr2line builds         : no
12:29:14     - WinDbg builds            : no
12:30:10     - WinDbgCached builds      : no

The two WinDbg tests tried to start arm64 binaries, which causes a requester to pop up if a desktop is available to the session the build is running in, or an infinite hang if it isn't.

**Comment by apolukhin** [comment]
Please, provide more info:
* What was the command line for b2?
* What version of Visual Studio do you use?
* What version of Boost and is it reproducible on 1.75 release?

**Comment by apolukhin** [comment]
Can not reproduce the issue. Please, provide a PR with fix if the issue still exists
